"""
Create precomposed versions of glyphs with combining diacritics where possible.
"""

import ufoLib2
from ufoLib2.objects.glyph import Glyph
from ufoLib2.objects.component import Component
from fontTools.misc.transform import Identity

from glyphsLib.glyphdata import GlyphData
from importlib.resources import files

from pathlib import Path

import unicodedata as ud

AUTOGEN_NOTE = "Generated by precompose.py\nIf this note is removed or altered then future runs will not update this, even if anchor positions have changed."


def getGlyphData() -> GlyphData:
    path = files("glyphsLib.data") / "GlyphData.xml"
    with path.open("rb") as f:
        return GlyphData.from_files(f)


gd = getGlyphData()
u2n = {int(k, 16): v["name"].replace('-', '.') for k, v in gd.unicodes.items()}

src_dir = Path(Path(__file__).resolve().parent, "../src/").resolve()
regular = ufoLib2.Font.open(
    (src_dir / "AnnotationMono_Regular.ufo").resolve(), lazy=True
)
reg_unis = {chr(u): g.name or f"uni{u:X}" for g in regular for u in g.unicodes}

for ufo in src_dir.glob("*.ufo"):
    font = ufoLib2.Font.open(ufo.resolve(), lazy=True)

    unis = {chr(u): g.name or f"uni{u:X}" for g in font for u in g.unicodes}

    # Clear any existing autogen'd glyphs.
    for g in font:
        if (g.note == AUTOGEN_NOTE):
            del g

    # Iterate through the basic multilingual plane and figure out
    # which characters we have the base glyphs to precompose.
    for i in range(65536):
        seq = ud.normalize("NFD", chr(i))

        if len(seq) < 2:
            continue
        if all([c in unis for c in seq]):
            base_name = unis[seq[0]]
            name = u2n[i] if i in u2n else f"uni{i:X}"
            print(f"{chr(i)} -> {seq} (U+{i:X}, {name})")

            base_alternates = [
                g for g in font.keys()
                if g == base_name or g.startswith(base_name + ".")
            ]

            for alt_base in base_alternates:
                suffix = alt_base[len(base_name):]
                out_name = name + suffix

                if (out_name in regular and regular[out_name].note != AUTOGEN_NOTE) or (
                    out_name in font and font[out_name].note != AUTOGEN_NOTE
                ):
                    continue

                components = [Component(alt_base)]

                for c in seq[1:]:
                    comb = font[unis[c]]

                    matches = []
                    for cmp in components[::-1]:
                        o = font[cmp.baseGlyph]
                        anchors = list(o.anchors)
                        for cpn in o.components:
                            for a in font[cpn.baseGlyph].anchors:
                                anchors.append(a)

                        for a in anchors:
                            for ca in comb.anchors:
                                if ca.name == f"_{a.name}":
                                    matches.append(
                                        (
                                            a.x + cmp.transformation.dx - ca.x,
                                            a.y + cmp.transformation.dy - ca.y,
                                        )
                                    )

                    t = Identity

                    if len(matches) > 0:
                        dx, dy = matches[0]
                        t = t.translate(dx, dy)
                    else:
                        t = t.translate(font[components[-1].baseGlyph].width, 0)

                    components.append(Component(unis[c], t))

                if out_name in font and font[out_name].note == AUTOGEN_NOTE:
                    del font[out_name]

                font.addGlyph(
                    Glyph(
                        out_name,
                        width=font[components[0].baseGlyph].width,
                        height=font[components[0].baseGlyph].height,
                        unicodes=[i] if suffix == "" else [],
                        components=components,
                        note=AUTOGEN_NOTE,
                    )
                )

    font.save()
